### ISSUE TITLE
Invoice API

### ISSUE THREAD

**Issue by tahseen09** [strix-inc/Restro_BE#8]
## Goal
* To finalize the invoice for the table (End of a customer's service at restaurant).

## Acceptance criteria
* All orders/kot should be present in the calculation.
* All duplicate dishes should be grouped together.

## TODO
Create Invoice
- [x] invoice ID to be supplied
- [x] PUT request to update the already created invoice(in KOT) with
- [x] Create dishes entry
- [x] Calculate total, etc.

Get Invoice
- [x] Use Invoice ID to grab invoice
- [x] Get invoices based on date filter, etc
